name: dependencies
inputs:
  configuration:
    required: true
  cache-key:
    required: true
runs:
  using: composite
  steps:
    - name: export custom recipes
      shell: bash
      run: |
        conan export external/snappy snappy/1.1.9@
        conan export external/soci soci/4.0.3@

    - name: Restore Conan cache
      id: cache-restore
      uses: actions/cache/restore@v4
      with:
        path: ~/.conan/data
        key: ${{ inputs.cache-key }}-${{ inputs.configuration }}-conan-${{ hashFiles('conanfile.py') }}
        restore-keys: |
          ${{ inputs.cache-key }}-${{ inputs.configuration }}-conan-
          ${{ inputs.cache-key }}-conan-

    - name: install dependencies
      if: steps.cache-restore.outputs.cache-hit != 'true'
      shell: bash
      run: |
        mkdir ${build_dir}
        cd ${build_dir}
        conan install \
          --output-folder . \
          --build missing \
          --settings build_type=${{ inputs.configuration }} \
          ..

    - name: Save Conan cache
      if: steps.cache-restore.outputs.cache-hit != 'true' && success()
      uses: actions/cache/save@v4
      with:
        path: ~/.conan/data
        key: ${{ inputs.cache-key }}-${{ inputs.configuration }}-conan-${{ hashFiles('conanfile.py') }}
