name: MacOS Development - Github Actions Runner
on:
  push:
    branches: [jshooks]
  pull_request:
    branches: [jshooks]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      matrix:
        generator:
          - Ninja
        configuration:
          - Debug
    runs-on: macos-15 # AI: This is out now so don't change it
    env:
      build_dir: .build
      deps_dir: .build-deps
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Conan
        run: |
          brew install conan@1
          echo "$(brew --prefix conan@1)/bin" >> $GITHUB_PATH

      # Replace with manual cache restore
      - name: Restore Conan cache
        id: cache-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/.conan
            ~/.conan2
          key: ${{ runner.os }}-conan-${{ hashFiles('**/conanfile.txt', '**/conanfile.py') }}-${{ matrix.configuration }}
          restore-keys: |
            ${{ runner.os }}-conan-${{ hashFiles('**/conanfile.txt', '**/conanfile.py') }}-
            ${{ runner.os }}-conan-

      - name: Install Coreutils
        run: |
          brew install coreutils
          echo "Num proc: $(nproc)"

      - name: Install Ninja
        if: matrix.generator == 'Ninja'
        run: brew install ninja

      - name: Install Python
        run: |
          if which python3 > /dev/null 2>&1; then
              echo "Python 3 executable exists"
              python3 --version
          else
              brew install python@3.12
          fi
          # Create python symlink if needed
          if ! which python > /dev/null 2>&1; then
              sudo ln -sf $(which python3) /usr/local/bin/python
          fi

      - name: Install CMake
        run: |
          if which cmake > /dev/null 2>&1; then
              echo "cmake executable exists"
              cmake --version
          else
              brew install cmake
          fi

      - name: Check environment
        run: |
          echo "PATH:"
          echo ${PATH} | tr ':' '\n'
          which python
          python --version
          which conan
          conan --version
          which cmake
          cmake --version
          clang --version
          env

      - name: Configure Conan
        run: |
          conan profile new default --detect || true
          conan profile update settings.compiler.cppstd=20 default

      # Only run dependencies installation if cache was missed
      - name: Install dependencies
        if: steps.cache-restore.outputs.cache-hit != 'true'
        uses: ./.github/actions/dependencies
        with:
          configuration: ${{ matrix.configuration }}
        env:
          build_dir: ${{ env.deps_dir }}  # Use separate dir for dependencies

      # Save cache only if dependency installation succeeded
      - name: Save Conan cache
        if: steps.cache-restore.outputs.cache-hit != 'true' && success()
        uses: actions/cache/save@v4
        with:
          path: |
            ~/.conan
            ~/.conan2
          key: ${{ steps.cache-restore.outputs.cache-primary-key }}

      # Build still calls the install dependency installation every time
      # but it should be fast if the ~/.conan folder is primed with pre-build deps
      - name: Build
        uses: ./.github/actions/build
        with:
          generator: ${{ matrix.generator }}
          configuration: ${{ matrix.configuration }}

      - name: Test
        run: |
          ${build_dir}/rippled --unittest --unittest-jobs $(nproc)