name: Nix Development - GA Runner
on:
  push:
    branches: [jshooks]
  pull_request:
    branches: [jshooks]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checkpatterns:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check for suspicious patterns
        run: |
          if [ -f "suspicious_patterns.sh" ]; then
            bash suspicious_patterns.sh
          else
            echo "Warning: suspicious_patterns.sh not found, skipping check"
            # Still exit with success since this is just for status check compatibility
            exit 0
          fi

  build-job:
    runs-on: ubuntu-latest
    needs: checkpatterns
    outputs:
      artifact_name: ${{ steps.set-artifact-name.outputs.artifact_name }}
    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc] # [gcc, clang]
        configuration: [Debug]
        include:
          - compiler: gcc
            cc: gcc-11
            cxx: g++-11
    #          - compiler: clang
    #            cc: clang-14
    #            cxx: clang++-14
    env:
      build_dir: .build
      deps_dir: .build-deps
      CACHE_VERSION: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build ${{ matrix.cc }} ${{ matrix.cxx }} ccache
          pip install --upgrade "conan<2"
          
      - name: Configure CCache
        run: |
          mkdir -p ~/.ccache # this will be used if it's there rather than ~/Library
          export CONF_PATH="${CCACHE_CONFIGPATH:-${CCACHE_DIR:-$HOME/.ccache}/ccache.conf}"
          mkdir -p $(dirname $CONF_PATH)
          echo "max_size = 2G" > $CONF_PATH
          echo "hash_dir = true" >> $CONF_PATH
          echo "compiler_check = content" >> $CONF_PATH
          ccache -p  # Print config for verification

      # Manual cache restore
      - name: Restore Conan cache
        id: cache-restore
        uses: actions/cache/restore@v4
        with:
          path: ~/.conan
          key: ${{ runner.os }}-conan-${{ matrix.compiler }}-${{ hashFiles('**/conanfile.txt', '**/conanfile.py') }}-${{ matrix.configuration }}
          restore-keys: |
            ${{ runner.os }}-conan-${{ matrix.compiler }}-${{ hashFiles('**/conanfile.txt', '**/conanfile.py') }}-
            ${{ runner.os }}-conan-${{ matrix.compiler }}-

      - name: Configure Conan
        run: |
          conan profile new default --detect || true
          conan profile update settings.compiler.cppstd=20 default
          conan profile update settings.compiler=${{ matrix.compiler }} default
          conan profile update settings.compiler.libcxx=libstdc++11 default
          conan profile update env.CC=/usr/bin/${{ matrix.cc }} default
          conan profile update env.CXX=/usr/bin/${{ matrix.cxx }} default
          conan profile update conf.tools.build:compiler_executables='{"c": "/usr/bin/${{ matrix.cc }}", "cpp": "/usr/bin/${{ matrix.cxx }}"}' default
          
          # Set correct compiler version based on compiler type
          if [ "${{ matrix.compiler }}" = "gcc" ]; then
            conan profile update settings.compiler.version=11 default
          elif [ "${{ matrix.compiler }}" = "clang" ]; then
            conan profile update settings.compiler.version=14 default
          fi

      # Only run dependency installation if cache miss
      - name: Install dependencies
        if: steps.cache-restore.outputs.cache-hit != 'true'
        uses: ./.github/actions/dependencies
        with:
          configuration: ${{ matrix.configuration }}
        env:
          build_dir: ${{ env.deps_dir }}  # Use separate dir for dependencies

      # Save cache only if dependencies action succeeded
      - name: Save Conan cache
        if: steps.cache-restore.outputs.cache-hit != 'true' && success()
        uses: actions/cache/save@v4
        with:
          path: ~/.conan
          key: ${{ steps.cache-restore.outputs.cache-primary-key }}

      - name: Check environment
        run: |
          echo "PATH: ${PATH}" | tr ':' '\n'
          conan --version
          cmake --version
          ${{ matrix.cc }} --version
          ${{ matrix.cxx }} --version

      - name: Generate safe branch name
        id: safe-branch
        run: |
          # Replace characters that aren't allowed in cache keys
          SAFE_BRANCH=$(echo "${{ github.ref_name }}" | tr -c 'a-zA-Z0-9_.-' '-')
          echo "safe_branch_name=${SAFE_BRANCH}" >> $GITHUB_OUTPUT

      - name: Restore ccache directory
        id: ccache-restore
        uses: actions/cache/restore@v4
        with:
          path: ~/.ccache
          key: ${{ runner.os }}-ccache-${{ env.CACHE_VERSION }}-${{ steps.safe-branch.outputs.safe_branch_name }}
          restore-keys: |
            ${{ runner.os }}-ccache-${{ env.CACHE_VERSION }}-
            ${{ runner.os }}-ccache-

      - name: Build
        uses: ./.github/actions/build
        with:
          generator: Ninja
          configuration: ${{ matrix.configuration }}
        env:
          # Make sure the build action receives the build_dir explicitly
          build_dir: ${{ env.build_dir }}

      # After your build step
      - name: Save ccache directory
        id: save-ccache
        if: success()
        uses: actions/cache/save@v4
        with:
          path: ~/.ccache
          # Reference the primary key from the restore step
          key: ${{ steps.ccache-restore.outputs.cache-primary-key }}

      - name: Save ccache with run_id fallback in case of lock contention
        if: steps.save-ccache.outcome == 'failure'
        uses: actions/cache/save@v4
        with:
          path: ~/.ccache
          key: ${{ steps.ccache-restore.outputs.cache-primary-key }}-${{ github.run_id }}

      - name: Set artifact name
        id: set-artifact-name
        run: |
          ARTIFACT_NAME="build-output-nix-${{ github.run_id }}-${{ matrix.compiler }}-${{ matrix.configuration }}"
          echo "artifact_name=${ARTIFACT_NAME}" >> "$GITHUB_OUTPUT"
          echo "Using artifact name: ${ARTIFACT_NAME}"

      - name: Debug build directory
        run: |
          echo "Checking build directory contents..."
          ls -la ${{ env.build_dir }} || echo "Build directory not found"

#      - name: Upload build artifacts
#        uses: actions/upload-artifact@v4
#        with:
#          name: ${{ steps.set-artifact-name.outputs.artifact_name }}
#          path: ${{ env.build_dir }}
#          retention-days: 1
#          include-hidden-files: true

      - name: Run tests
        run: |
          # TODO
          .build/rippled --unittest --unittest-jobs $(nproc)

  build:
    runs-on: ubuntu-latest
    needs: build-job
    steps:
      - name: Dummy Build
        run: |
          echo "Dummy build relies upon build-job matrix"

  tests:
    runs-on: ubuntu-latest
    needs: build-job
    steps:
      - name: Run tests
        run: |
          echo "Dummy tests relies upon build-job matrix"
