name: Nix Development - GA Runner
on:
  push:
    branches: [jshooks]
  pull_request:
    branches: [jshooks]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checkpatterns:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check for suspicious patterns
        run: |
          if [ -f "suspicious_patterns.sh" ]; then
            bash suspicious_patterns.sh
          else
            echo "Warning: suspicious_patterns.sh not found, skipping check"
            # Still exit with success since this is just for status check compatibility
            exit 0
          fi

  build:
    runs-on: ubuntu-latest
    needs: checkpatterns
    outputs:
      artifact_name: ${{ steps.set-artifact-name.outputs.artifact_name }}
    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc] # [gcc, clang]
        configuration: [Debug]
        include:
          - compiler: gcc
            cc: gcc-11
            cxx: g++-11
    #          - compiler: clang
    #            cc: clang-14
    #            cxx: clang++-14
    env:
      build_dir: .build
      deps_dir: .build-deps
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build ${{ matrix.cc }} ${{ matrix.cxx }}
          pip install --upgrade "conan<2"

      # Manual cache restore
      - name: Restore Conan cache
        id: cache-restore
        uses: actions/cache/restore@v4
        with:
          path: ~/.conan
          key: ${{ runner.os }}-conan-${{ matrix.compiler }}-${{ hashFiles('**/conanfile.txt', '**/conanfile.py') }}-${{ matrix.configuration }}
          restore-keys: |
            ${{ runner.os }}-conan-${{ matrix.compiler }}-${{ hashFiles('**/conanfile.txt', '**/conanfile.py') }}-
            ${{ runner.os }}-conan-${{ matrix.compiler }}-

      - name: Configure Conan
        run: |
          conan profile new default --detect || true
          conan profile update settings.compiler.cppstd=20 default
          conan profile update settings.compiler=${{ matrix.compiler }} default
          conan profile update settings.compiler.libcxx=libstdc++11 default
          conan profile update env.CC=/usr/bin/${{ matrix.cc }} default
          conan profile update env.CXX=/usr/bin/${{ matrix.cxx }} default
          conan profile update conf.tools.build:compiler_executables='{"c": "/usr/bin/${{ matrix.cc }}", "cpp": "/usr/bin/${{ matrix.cxx }}"}' default
          
          # Set correct compiler version based on compiler type
          if [ "${{ matrix.compiler }}" = "gcc" ]; then
            conan profile update settings.compiler.version=11 default
          elif [ "${{ matrix.compiler }}" = "clang" ]; then
            conan profile update settings.compiler.version=14 default
          fi

      # Only run dependency installation if cache miss
      - name: Install dependencies
        if: steps.cache-restore.outputs.cache-hit != 'true'
        uses: ./.github/actions/dependencies
        with:
          configuration: ${{ matrix.configuration }}
        env:
          build_dir: ${{ env.deps_dir }}  # Use separate dir for dependencies

      # Save cache only if dependencies action succeeded
      - name: Save Conan cache
        if: steps.cache-restore.outputs.cache-hit != 'true' && success()
        uses: actions/cache/save@v4
        with:
          path: ~/.conan
          key: ${{ steps.cache-restore.outputs.cache-primary-key }}

      - name: Check environment
        run: |
          echo "PATH: ${PATH}" | tr ':' '\n'
          conan --version
          cmake --version
          ${{ matrix.cc }} --version
          ${{ matrix.cxx }} --version

      # After your Conan cache restore but before the build step
      - name: Restore build directory cache
        id: build-cache-restore
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.build_dir }}
          # Primary key without SHA - much higher hit probability
          key: ${{ runner.os }}-build-${{ matrix.compiler }}-${{ matrix.configuration }}-${{ github.ref_name }}-${{ hashFiles('**/conanfile.txt', '**/conanfile.py') }}
          restore-keys: |
            # Same branch, different dependencies
            ${{ runner.os }}-build-${{ matrix.compiler }}-${{ matrix.configuration }}-${{ github.ref_name }}-
            # Same compiler/config, any branch
            ${{ runner.os }}-build-${{ matrix.compiler }}-${{ matrix.configuration }}-

      - name: Build
        uses: ./.github/actions/build
        with:
          generator: Ninja
          configuration: ${{ matrix.configuration }}
        env:
          # Make sure the build action receives the build_dir explicitly
          build_dir: ${{ env.build_dir }}

      # After your build step but before tests or artifact uploads
      - name: Save build directory cache
        if: success()
        uses: actions/cache/save@v4
        with:
          path: ${{ env.build_dir }}
          # Reference the primary key from the restore step
          key: ${{ steps.build-cache-restore.outputs.cache-primary-key }}


      - name: Set artifact name
        id: set-artifact-name
        run: |
          ARTIFACT_NAME="build-output-nix-${{ github.run_id }}-${{ matrix.compiler }}-${{ matrix.configuration }}"
          echo "artifact_name=${ARTIFACT_NAME}" >> "$GITHUB_OUTPUT"
          echo "Using artifact name: ${ARTIFACT_NAME}"

      - name: Debug build directory
        run: |
          echo "Checking build directory contents..."
          ls -la ${{ env.build_dir }} || echo "Build directory not found"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.set-artifact-name.outputs.artifact_name }}
          path: ${{ env.build_dir }}
          retention-days: 1

  tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build.outputs.artifact_name }}
          path: .build

      - name: Set executable permissions
        run: |
          chmod +x .build/rippled

      - name: Run tests
        run: |
          .build/rippled --unittest --unittest-jobs $(nproc)